# Generated by Django 5.1.3 on 2024-12-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_recruiter_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='recruiter_company_name',
            new_name='company',
        ),
    ]
